### ISSUE TITLE
NodeCount is wrong in header

### ISSUE THREAD

**Issue by KururuLABO** [angelsl/ms-wz2nx#6]
i tried to testing nxfile from wz2nx i got wrong information in header.
When i converted wz by wz2nx and im tried to use 2 lib to read it then i got this result.

reNX(c#)
Read header got : 24557
Loop all node got : 24631
Recursive all node got : 24631

pkgNX(java)
Read header got : 24557
Recursive all node got : 24631

different node size : 24631(after loops) - 24557(from header) = 74 nodes.

**Comment by angelsl** [comment]
Not a bug.

This is due to UOLs. In the NX format, there are no UOLs. Instead, we just duplicate the node pointed to by the UOL in place of the UOL element. The duplicated nodes will point to the children of the _original element_.

So when you recurse all nodes, you're actually hitting some nodes more than once. The file actually only contains the number of nodes specified in the header.

**Comment by retep998** [comment]
Also there can be nodes in the node table which do not have lineage back to the root node. Although wz2nx will never do that, it is valid according to spec.
